models:
  lessons:
    +materialized: table # Default all SQL models to be materialised as tables
    +persist_docs: # Writes all of our column descriptions into BigQuery!
      relation: true
      columns: true
    # Table deletes 168 hours (7 days) after creation (or 1 hour if it's a CI test)
    +hours_to_expiration: |
      {% if target.name == 'test' %} 1
      {% else %} 168
      {% endif %}